import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, '..');
const versionFile = resolve(projectRoot, 'src', 'version.js');
const packageJsonFile = resolve(projectRoot, 'package.json');
const serviceWorkerFile = resolve(projectRoot, 'public', 'sw.js');

function run(command) {
  try {
    return execSync(command, {
      cwd: projectRoot,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
  } catch {
    return '';
  }
}

const commitCount = process.env.VERCEL_GIT_COMMIT_SHA
  ? run('git rev-list --count HEAD') || '0'
  : run('git rev-list --count HEAD') || '0';
const shortSha = (process.env.VERCEL_GIT_COMMIT_SHA || run('git rev-parse --short HEAD') || 'local').slice(0, 7);

const buildTime = new Intl.DateTimeFormat('sv-SE', {
  timeZone: 'Asia/Seoul',
  year: 'numeric',
  month: '2-digit',
  day: '2-digit',
  hour: '2-digit',
  minute: '2-digit',
  hour12: false,
}).format(new Date()).replace(',', '');

const versionNumber = Number.parseInt(commitCount, 10);
const appVersion = Number.isFinite(versionNumber) && versionNumber > 0 ? `v${versionNumber}` : 'v0';
const appBuild = `${buildTime} (${shortSha})`;

const content = [
  '// Auto-generated by scripts/generate-version.mjs',
  `export const APP_VERSION = '${appVersion}';`,
  `export const APP_BUILD = '${appBuild}';`,
  `export const APP_COMMIT = '${shortSha}';`,
  '',
].join('\n');

writeFileSync(versionFile, content, 'utf8');

const packageJson = JSON.parse(readFileSync(packageJsonFile, 'utf8'));
packageJson.version = Number.isFinite(versionNumber) && versionNumber > 0 ? `0.${versionNumber}.0` : '0.0.0';
writeFileSync(packageJsonFile, `${JSON.stringify(packageJson, null, 2)}\n`, 'utf8');

const serviceWorkerSource = readFileSync(serviceWorkerFile, 'utf8');
const updatedServiceWorker = serviceWorkerSource.replace(
  /const CACHE = 'daymate-[^']+';/,
  `const CACHE = 'daymate-${shortSha}';`,
);
writeFileSync(serviceWorkerFile, updatedServiceWorker, 'utf8');

console.log(`Generated ${appVersion} ${appBuild}`);