const S = {
  app: {
    background: "var(--dm-bg)",
    color: "var(--dm-text)",
    fontFamily: "'Inter','Pretendard','Apple SD Gothic Neo',sans-serif",
    minHeight: "100vh",
    width: "100%",
  },
  phone: {
    width: "100%",
    maxWidth: 430,
    minHeight: "100vh",
    margin: "0 auto",
    background: "var(--dm-phone)",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    boxShadow: "0 0 60px rgba(0,0,0,.5)",
    position: "relative",
  },
  content: {
    flex: 1,
    width: "100%",
    minWidth: 0,
    overflowY: "auto",
    overflowX: "auto",
    paddingBottom: 90,
    boxSizing: "border-box",
    position: "relative",
    zIndex: 1,
  },
  topbar: {
    padding: "18px 20px 12px",
    borderBottom: "1px solid var(--dm-border)",
    background: "var(--dm-nav)",
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    position: "relative",
    zIndex: 2,
  },
  title: {
    fontSize: 18,
    fontWeight: 900,
    fontFamily: "'Plus Jakarta Sans', sans-serif",
  },
  sub: { fontSize: 12, color: "var(--dm-sub)", marginTop: 2 },
  card: {
    background: "var(--dm-card)",
    border: "1px solid var(--dm-border)",
    borderRadius: 16,
    padding: "14px 14px",
    margin: "0 16px 10px",
    boxSizing: "border-box",
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
    boxShadow: "0 4px 24px rgba(0,0,0,0.2), inset 0 1px 0 rgba(255,255,255,0.06)",
    position: "relative",
    zIndex: 1,
  },
  sectionTitle: {
    padding: "22px 16px 8px",
    fontSize: 17,
    letterSpacing: "0.01em",
    color: "var(--dm-text)",
    fontWeight: 900,
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    textTransform: "none",
    display: "flex",
    alignItems: "center",
    gap: 8,
    position: "relative",
    zIndex: 1,
  },
  sectionEmoji: {
    fontSize: 22,
    lineHeight: 1,
  },
  input: {
    width: "100%",
    padding: "12px 12px",
    borderRadius: 10,
    background: "var(--dm-input)",
    border: "1.5px solid var(--dm-border)",
    color: "var(--dm-text)",
    fontSize: 14,
    fontFamily: "inherit",
    outline: "none",
    boxSizing: "border-box",
  },
  btn: {
    width: "100%",
    marginTop: 10,
    padding: "13px 14px",
    borderRadius: 12,
    border: "none",
    background: "linear-gradient(135deg, #4B6FFF, #818cf8)",
    color: "#fff",
    fontSize: 14,
    fontWeight: 900,
    cursor: "pointer",
    fontFamily: "inherit",
    boxShadow: "0 4px 20px rgba(75,111,255,.35), inset 0 1px 0 rgba(255,255,255,.15)",
    letterSpacing: "0.01em",
  },
  btnGhost: {
    width: "100%",
    marginTop: 10,
    padding: "12px 14px",
    borderRadius: 12,
    border: "1.5px solid var(--dm-border2)",
    background: "rgba(255,255,255,0.04)",
    color: "var(--dm-sub)",
    fontSize: 14,
    fontWeight: 800,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  pill: (on) => ({
    padding: "7px 12px",
    borderRadius: 999,
    border: `1.5px solid ${on ? "rgba(108,142,255,.5)" : "var(--dm-border)"}`,
    background: on ? "rgba(108,142,255,.15)" : "var(--dm-pill-off)",
    color: on ? "#818cf8" : "var(--dm-sub)",
    fontSize: 12,
    fontWeight: 800,
    cursor: "pointer",
    whiteSpace: "nowrap",
  }),
  bottomNav: {
    position: "fixed",
    bottom: 0,
    left: "50%",
    transform: "translateX(-50%)",
    width: "100%",
    maxWidth: 430,
    background: "var(--dm-nav)",
    backdropFilter: "blur(20px)",
    WebkitBackdropFilter: "blur(20px)",
    borderTop: "1px solid var(--dm-border)",
    padding: "10px 0 26px",
    display: "flex",
    justifyContent: "space-around",
    zIndex: 100,
  },
  navItem: (active) => ({
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 3,
    fontSize: 11,
    color: active ? "#818cf8" : "var(--dm-muted)",
    cursor: "pointer",
    padding: "4px 10px",
    border: "none",
    background: "transparent",
    fontFamily: "inherit",
  }),
  toast: {
    position: "fixed",
    bottom: 105,
    left: "50%",
    transform: "translateX(-50%)",
    background: "var(--dm-toast-bg)",
    border: "1px solid var(--dm-toast-bd)",
    color: "#4ADE80",
    padding: "10px 18px",
    borderRadius: 999,
    fontSize: 13,
    fontWeight: 800,
    zIndex: 999,
    boxShadow: "0 4px 16px rgba(0,0,0,.35)",
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
  },
};

export default S;
