const S = {
  app: {
    background: "var(--dm-bg)",
    color: "var(--dm-text)",
    fontFamily: "'Pretendard','Apple SD Gothic Neo',sans-serif",
    minHeight: "100vh",
    display: "flex",
    justifyContent: "center",
    width: "100vw",
  },
  phone: {
    width: "100%",
    maxWidth: "100%",
    minHeight: "100vh",
    background: "var(--dm-phone)",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  content: {
    flex: 1,
    width: "100%",
    minWidth: 0,
    overflowY: "auto",
    overflowX: "auto",
    paddingBottom: 90,
    boxSizing: "border-box",
  },
  topbar: {
    padding: "18px 20px 12px",
    borderBottom: "1px solid var(--dm-border)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  title: { fontSize: 18, fontWeight: 900 },
  sub: { fontSize: 12, color: "var(--dm-sub)", marginTop: 2 },
  card: {
    background: "var(--dm-card)",
    border: "1px solid var(--dm-border)",
    borderRadius: 14,
    padding: "14px 14px",
    margin: "0 16px 10px",
    boxSizing: "border-box",
  },
  sectionTitle: {
    padding: "18px 16px 8px",
    fontSize: 14,
    letterSpacing: "0.02em",
    color: "var(--dm-text)",
    fontWeight: 900,
    textTransform: "none",
  },
  input: {
    width: "100%",
    padding: "12px 12px",
    borderRadius: 10,
    background: "var(--dm-input)",
    border: "1.5px solid var(--dm-border)",
    color: "var(--dm-text)",
    fontSize: 14,
    fontFamily: "inherit",
    outline: "none",
    boxSizing: "border-box",
  },
  btn: {
    width: "100%",
    marginTop: 10,
    padding: "12px 14px",
    borderRadius: 12,
    border: "none",
    background: "linear-gradient(135deg,#4B6FFF,#6C8EFF)",
    color: "#fff",
    fontSize: 14,
    fontWeight: 900,
    cursor: "pointer",
    fontFamily: "inherit",
    boxShadow: "0 4px 18px rgba(108,142,255,.25)",
  },
  btnGhost: {
    width: "100%",
    marginTop: 10,
    padding: "12px 14px",
    borderRadius: 12,
    border: "1.5px solid var(--dm-border2)",
    background: "transparent",
    color: "var(--dm-sub)",
    fontSize: 14,
    fontWeight: 800,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  pill: (on) => ({
    padding: "7px 12px",
    borderRadius: 999,
    border: `1.5px solid ${on ? "#6C8EFF" : "var(--dm-border)"}`,
    background: on ? "rgba(108,142,255,.12)" : "var(--dm-pill-off)",
    color: on ? "#6C8EFF" : "var(--dm-sub)",
    fontSize: 12,
    fontWeight: 800,
    cursor: "pointer",
    whiteSpace: "nowrap",
  }),
  bottomNav: {
    position: "fixed",
    bottom: 0,
    left: "50%",
    transform: "translateX(-50%)",
    width: "100%",
    maxWidth: 430,
    background: "var(--dm-nav)",
    borderTop: "1px solid var(--dm-border)",
    padding: "10px 0 26px",
    display: "flex",
    justifyContent: "space-around",
    zIndex: 100,
  },
  navItem: (active) => ({
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 3,
    fontSize: 11,
    color: active ? "#6C8EFF" : "var(--dm-muted)",
    cursor: "pointer",
    padding: "4px 10px",
    border: "none",
    background: "transparent",
    fontFamily: "inherit",
  }),
  toast: {
    position: "fixed",
    bottom: 105,
    left: "50%",
    transform: "translateX(-50%)",
    background: "var(--dm-toast-bg)",
    border: "1px solid var(--dm-toast-bd)",
    color: "#4ADE80",
    padding: "10px 18px",
    borderRadius: 999,
    fontSize: 13,
    fontWeight: 800,
    zIndex: 999,
    boxShadow: "0 4px 16px rgba(0,0,0,.35)",
  },
};

export default S;
